=== pcaz/Neo4j-genere/Neo4j-genere.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://Neo4j_genere/xml" targetNamespace="http://Neo4j_genere/xml"
	elementFormDefault="qualified">

<xsd:element name="database">
<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="name" />
			<xsd:element name="number" type="xsd:integer" />
			<xsd:element name="fields" type="field" minOccurs="1" maxOccurs="unbounded" /> 
		</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:complexType name="field">
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="int" type="ints" />
			<xsd:element name="string" type="strings" />
			<xsd:element name="date" type="dates" />
		</xsd:choice> 
</xsd:complexType>

<xsd:complexType name="ints">
	<xsd:sequence>
		<xsd:element name="name" />
		<xsd:element name="optionnal" minOccurs="0"/>
		<xsd:element name="space" type="intSpace" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="intSpace">
	<xsd:sequence>
		<xsd:choice>
			<xsd:element name="identifiant" nillable="true" />
			<xsd:element name="values">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="min" type="xsd:integer" />
						<xsd:element name="max" type="xsd:integer" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="strings">
	<xsd:sequence>
		<xsd:element name="name" />
				<xsd:element name="optionnal" minOccurs="0"/>
		<xsd:element name="space" type="stringSpace" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="stringSpace">
	<xsd:sequence>
		<xsd:choice>
				<xsd:element name="long">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="min" type="xsd:integer" />
							<xsd:element name="max" type="xsd:integer" />
					</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="regular" type="xsd:string" />
		</xsd:choice>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dates">
	<xsd:sequence>
		<xsd:element name="name" />
		<xsd:element name="optionnal" minOccurs="0"/>
		<xsd:element name="space" type="dateSpace" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="dateSpace">
	<xsd:sequence>
					<xsd:element name="after" type="xsd:date" />
					<xsd:element name="before" type="xsd:date" />
	</xsd:sequence>
</xsd:complexType>

</xsd:schema>

=== pcaz/Neo4j-genere/Neo4j-genere.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://Neo4j_genere/xml" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="file:///home/pascaz10/eclipse-workspace/Neo4j-genere/Neo4j-genere.xsd">

	<name>Person</name>
	<number>1353</number>
	<fields>
		<int>
			<name>id</name>
			<space>
				<identifiant/>
			</space>
		</int>
		<string>
			<name>name</name>
			<space>
				<iterate/>
			</space>
		</string>
		<date>
			<name>birthDate</name>
			
			<space>
				<after>1970-01-01</after>
				<before>1990-01-01</before>
			</space>
		</date>
		<string>
			<name>email</name>
			<optionnal>50</optionnal>
			<space>
				<regular>eval(name)@example.com</regular>
			</space>
		</string>
	</fields>
</database>
